import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const CONFIG_PATH = path.join(__dirname, '..', 'drive-sync', 'config.json')
const CONTENT_DIR = path.join(__dirname, '..', 'content', 'drive')

const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'))

// ---------------------------------------------------------------------------
// CSV parser — handles quoted fields containing commas and newlines
// ---------------------------------------------------------------------------

function parseCSV(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false

  for (let i = 0; i < text.length; i++) {
    const ch = text[i]
    const next = text[i + 1]

    if (inQuotes) {
      if (ch === '"' && next === '"') { field += '"'; i++ }
      else if (ch === '"') { inQuotes = false }
      else { field += ch }
    } else {
      if (ch === '"') { inQuotes = true }
      else if (ch === ',') { row.push(field); field = '' }
      else if (ch === '\n') { row.push(field); rows.push(row); row = []; field = '' }
      else if (ch === '\r') { /* skip */ }
      else { field += ch }
    }
  }
  if (field || row.length) { row.push(field); rows.push(row) }
  return rows
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const OFFICE_LABELS = {
  'application/vnd.google-apps.document':     'Word (.docx)',
  'application/vnd.google-apps.spreadsheet':  'Excel (.xlsx)',
  'application/vnd.google-apps.presentation': 'PowerPoint (.pptx)',
  'application/vnd.google-apps.drawing':      'SVG (.svg)',
}

function officeLabel(mimeType) {
  return OFFICE_LABELS[mimeType] || 'Office file'
}

function safePath(p) {
  return p.replace(/[<>:"|?*]/g, '_')
}

function toYamlValue(value) {
  if (typeof value !== 'string') return value
  if (value.includes(':') || value.includes('#') || value.includes('"')) {
    return `"${value.replace(/"/g, '\\"')}"`
  }
  return value
}

function frontmatter(fields) {
  const lines = ['---']
  for (const [key, val] of Object.entries(fields)) {
    if (val === '' || val == null) continue
    lines.push(`${key}: ${toYamlValue(String(val))}`)
  }
  lines.push('---')
  return lines.join('\n')
}

/**
 * Build an HTML icon link for use in a markdown table cell.
 * Returns '–' if href is empty (no export available for this file type).
 */
function iconLink(href, iconUrl, title, alt) {
  if (!href) return '–'
  return `<a href="${href}" title="${title}" target="_blank" rel="noopener"><img src="${iconUrl}" width="24" height="24" alt="${alt}" style="vertical-align:middle"></a>`
}

/**
 * Render a markdown table of files with thumbnail, Drive / Office / PDF icon links.
 * iconBase — absolute URL prefix, e.g. https://example.com/static/icons
 */
function buildFileTable(files, iconBase) {
  const driveIcon  = `${iconBase}/drive.svg`
  const officeIcon = `${iconBase}/office.svg`
  const pdfIcon    = `${iconBase}/pdf.svg`

  const headerRow = '| Preview | File | Drive | Office | PDF |'
  const separator = '|:-------:|------|:-----:|:------:|:---:|'

  const rows = files.map(f => {
    // Escape pipe characters in file names to avoid breaking the table
    const name      = (f['Name'] || 'Unnamed').replace(/\|/g, '\\|')
    const driveUrl  = f['URL']
    const officeUrl = f['Export (Office)']
    const pdfUrl    = f['Export (PDF)']
    const mimeType  = f['MIME Type']

    // Thumbnail — generated by Apps Script, stored in Drive, URL in sheet
    const thumbUrl  = f['Thumbnail URL']
    const thumbCell = thumbUrl
      ? `<a href="${driveUrl}" target="_blank" rel="noopener"><img src="${thumbUrl}" width="120" alt="Preview of ${name}" style="border-radius:4px;vertical-align:middle"></a>`
      : ''

    const driveCell  = iconLink(driveUrl,  driveIcon,  'Open in Google Drive',                 'Open in Drive')
    const officeCell = iconLink(officeUrl, officeIcon, `Download as ${officeLabel(mimeType)}`,  'Download Office')
    const pdfCell    = iconLink(pdfUrl,    pdfIcon,    'Download as PDF',                       'Download PDF')

    return `| ${thumbCell} | **${name}** | ${driveCell} | ${officeCell} | ${pdfCell} |`
  })

  return [headerRow, separator, ...rows].join('\n')
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  if (!config.csvUrl || config.csvUrl === 'YOUR_PUBLISHED_CSV_URL_HERE') {
    console.error('Set csvUrl in drive-sync/config.json before running.')
    process.exit(1)
  }

  // Icon base URL — strip trailing slash so we can always append /drive.svg etc.
  const siteUrl  = (config.siteUrl || '').replace(/\/$/, '')
  // Quartz copies quartz/static/ → public/static/, so icons live at /static/icons/
  const iconBase = siteUrl ? `${siteUrl}/static/icons` : '/static/icons'

  console.log('Fetching Drive structure from Google Sheets…')
  const res = await fetch(config.csvUrl)
  if (!res.ok) throw new Error(`CSV fetch failed: ${res.status} ${res.statusText}`)
  const csv = await res.text()

  const [headerRow, ...dataRows] = parseCSV(csv)
  const headers = headerRow.map(h => h.trim())

  const data = dataRows
    .map(row => Object.fromEntries(headers.map((h, i) => [h, (row[i] ?? '').trim()])))
    .filter(row => row['File ID'])

  const rootRow = data.find(row => row['Depth'] === '0')
  if (!rootRow) throw new Error('Could not find root folder row (Depth = 0)')
  const rootName = rootRow['Name']

  // ------------------------------------------------------------------
  // Build a map of each folder's direct children (files + subfolders)
  // keyed by File ID
  // ------------------------------------------------------------------
  const childrenOf = new Map() // folderId → { files: Row[], subfolders: Row[] }

  for (const row of data) {
    const parentId = row['Parent ID']
    if (!parentId) continue
    if (!childrenOf.has(parentId)) {
      childrenOf.set(parentId, { files: [], subfolders: [] })
    }
    const bucket = childrenOf.get(parentId)
    if (row['Type'] === 'Folder') {
      bucket.subfolders.push(row)
    } else {
      bucket.files.push(row)
    }
  }

  // Clear previously generated pages
  if (fs.existsSync(CONTENT_DIR)) fs.rmSync(CONTENT_DIR, { recursive: true })

  let generated = 0

  // Helper: relative path from the root folder name
  function relPath(fullPath) {
    if (fullPath === rootName) return ''
    if (fullPath.startsWith(rootName + '/')) return fullPath.slice(rootName.length + 1)
    return fullPath
  }

  for (const row of data) {
    if (row['Type'] !== 'Folder') continue   // only process folders

    const folderId = row['File ID']
    const isRoot   = row['Depth'] === '0'
    const rel      = relPath(row['Full Path'])

    const { files = [], subfolders = [] } = childrenOf.get(folderId) || {}
    const hasFiles = files.length > 0
    const hasSubs  = subfolders.length > 0

    // ------------------------------------------------------------------
    // Folder categorisation:
    //
    // Every folder always gets an index.md so its title is available to
    // the parent FolderPage card grid (folders without index.md show as
    // "Untitled" in parent listings).  The Quartz FolderContent component
    // renders BOTH the markdown body AND the subfolder card grid, so
    // having an index.md does NOT suppress the card grid.
    //
    //  • Folders with files (leaf or mixed): frontmatter + file table
    //  • Pure-subfolder / empty folders:     frontmatter only (body empty)
    // ------------------------------------------------------------------

    let body = '\n'

    if (hasSubs && hasFiles) {
      // Mixed: file table only — FolderContent renders subfolder cards automatically
      body += buildFileTable(files, iconBase) + '\n'
    } else if (hasFiles) {
      // Leaf: just the file table
      body += buildFileTable(files, iconBase) + '\n'
    }
    // Pure-subfolder (any level) or empty: body stays as '\n'
    // FolderContent will render the card grid from the trie regardless

    const fm = frontmatter({
      title: row['Name'],
      date:  row['Modified Date'],
    })

    const dir        = rel ? path.join(CONTENT_DIR, safePath(rel)) : CONTENT_DIR
    const outputPath = path.join(dir, 'index.md')

    fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(outputPath, fm + body, 'utf8')
    generated++
  }

  console.log(`Done — generated ${generated} folder pages in content/drive/`)
}

main().catch(err => { console.error(err); process.exit(1) })
